// Regenerates src/lib/abi/*.ts from the Foundry contracts.
// Usage: pnpm sync-abi   (requires `forge` on PATH)
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const contractsDir = join(root, "..", "contracts");

const targets = [
  { contract: "TrueAlert", exportName: "trueAlertAbi", file: "trueAlert.ts" },
  { contract: "MockUSDC", exportName: "mockUsdcAbi", file: "mockUsdc.ts" },
];

for (const { contract, exportName, file } of targets) {
  const abi = execFileSync("forge", ["inspect", contract, "abi", "--json"], {
    cwd: contractsDir,
    encoding: "utf8",
  });
  const body = JSON.stringify(JSON.parse(abi), null, 2);
  const out = `// Generated by scripts/sync-abi.mjs from contracts/src/${contract}.sol — do not edit.\nexport const ${exportName} = ${body} as const;\n`;
  writeFileSync(join(root, "src", "lib", "abi", file), out);
  console.log(`wrote src/lib/abi/${file}`);
}
